### ISSUE TITLE
Event handler throw error even though email verification is persisted

### ISSUE THREAD

**Issue by sammkj** [plustwo/plustwo#20]
# Bug

### Expected Behavior

No errors at all.

### Actual Behavior

Throws the following error:

```
[error] GenServer #PID<0.503.0> terminating
** (CaseClauseError) no case clause matching: {:error, "account uuid does not exist"}
    (commanded) lib/commanded/event/handler.ex:101: anonymous fn/2 in Commanded.Event.Handler.handle_info/2
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    (commanded) lib/commanded/event/handler.ex:96: Commanded.Event.Handler.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:events, [%Commanded.EventStore.RecordedEvent{causation_id: nil, correlation_id: "dca34996-7c08-48b6-853d-0c6f6130e7a8", created_at: ~N[2017-09-05 18:49:31.495893], data: %Plustwo.Domain.Accounts.Events.AccountRegistered{email: "samkj.ks@gmail.com", email_type: 0, handle_name: "samkj", is_activated: true, is_contributor: false, is_email_verified: false, is_employee: false, is_org: false, is_suspended: false, joined_at: nil, uuid: "af3b4fa8-e1ac-40e7-acca-4ca84976ae07"}, event_number: 1, event_type: "Elixir.Plustwo.Domain.Accounts.Events.AccountRegistered", metadata: %{}, stream_id: 1, stream_version: 1}]}
State: %Commanded.Event.Handler{handler_module: Plustwo.Domain.Accounts.Workflows.SendPrimaryEmailVerificationCode, handler_name: "Accounts.Workflows.SendEmailVerificationCode", last_seen_event: nil, subscribe_from: :origin, subscription: #PID<0.516.0>}
```

**Comment by sammkj** [comment]
This only happens when the app first runs.

**Comment by sammkj** [comment]
We will let it crash and restart.
